#-------------------------------
# Site Settings
title: Johar Singh
logo: "/images/logo.svg"
logo_dark: "/images/logo-dark.svg"
description: I craft learning experiences that respect your intelligence, reward your time, and help you build meaningful skills.
color_scheme: auto


#-------------------------------
# Author Settings
author_name: Johar Singh


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    - title: "Services"
      url: "/services/"
    - title: "Portfolio"
      url: "/portfolio/"
    - title: "Blog"
      url: "/blog/"
    - title: "Contact"
      url: "/contact/"


#-------------------------------
# Social Settings
social:
- {icon: "fa-brands fa-linkedin", link: "https://www.linkedin.com/in/joharsingh/"}


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: '<em class="hero__title__accent">Outcome-oriented</em> learning solutions.'
  hero_description: I craft learning experiences that respect your intelligence, reward your time, and help you build meaningful skills.
  hero_image: "/images/Selkie-background.webp"
  hero_button_contact: Get in Touch
  hero_button_about: About Me


#-------------------------------
# Projects Settings
section_projects_title: Portfolio


#-------------------------------
# Testimonials Section
section_testimonials:
  enable: false


#-------------------------------
# Blog Section
section_blog_title: Blog Posts


#-------------------------------
# Tags Section
section_tags_title: Explore Topics


#-------------------------------
# Newsletter Settings (Kit)
newsletter_settings:
  enable: true
  newsletter_action: "https://app.kit.com/forms/9658065/subscriptions"
  newsletter_title: "Stay connected."


#-------------------------------
# Footer Settings
footer_description: I craft learning solutions that build capability and improve performance outcomes.


#-------------------------------
# Footer Navigation Settings
footer_menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    - title: "Services"
      url: "/services/"
    - title: "Portfolio"
      url: "/portfolio/"
    - title: "Blog"
      url: "/blog/"
    - title: "Contact"
      url: "/contact/"


#-------------------------------
# Contact Settings
contact:
  formspree_id: "mzdlqrel"
  description: If you want to team up on your next project, shoot me a message to get started. Tell me a bit about your goals, timeline, and any specific challenges you want to address.


#-------------------------------
# Comment Section (Disqus)
disqus_identifier:


#-------------------------------
# Google Analytics
google_analytics:
